### ISSUE TITLE
retext : won't start

### ISSUE THREAD

**Issue by deogracia** [deogracia/chakraos-ccr-my-contrib#18]
due to commit:179db830b7efa5fa3cdc1aee765566677e51a3b0

```
Using configuration file: ~/.config/ReText project/ReText.conf
Warning: no markups are available!
Traceback (most recent call last):
  File "/usr/bin/retext", line 81, in <module>
    main()
  File "/usr/bin/retext", line 76, in main
    window.createNew(inputData)
  File "/usr/lib/python3.5/site-packages/ReText/window.py", line 607, in createNew
    self.createTab("")
  File "/usr/lib/python3.5/site-packages/ReText/window.py", line 396, in createTab
    previewState=int(globalSettings.livePreviewByDefault))
  File "/usr/lib/python3.5/site-packages/ReText/tab.py", line 53, in __init__
    self.highlighter.docType = self.markup.name
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by deogracia** [comment]
it orks now. I don't remember if I did something
